name: Scrape YOK
on:
  workflow_dispatch:
    inputs:
      database_url:
        description: "URL of MySQL database"
        required: true
        type: string
      concurrent_requests:
        description: "How many concurrent requests should be made during scraping"
        required: false
        type: string
jobs:
  scrape:
    name: Scrapes all universities and teachers from YOK
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ inputs.database_url }}
      CONCURRENT_REQUESTS: ${{ inputs.concurrent_requests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run scraper
        run: node tools/university-scraper/index.js
      - name: Save output artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: tools/university-scraper/output.json
      - name: Upload data to database
        run: node tools/university-scraper/database.js
